### ISSUE TITLE
toLocaleString() not working

### ISSUE THREAD

**Issue by andreaparr** [andreaparr/water-ownership#13]
Trying to add commas and I'm not seeing any reason why toLocaleString() shouldn't work. Suggestions? What am I missing?

**Comment by rgdonohue** [comment]
The toLocaleString() method needs to be invoked on a Numeric value, not a string. So can first convert it to a Number, and then use the method.

`Number(layer.feature.properties.Population).toLocaleString()`

See: https://github.com/andreaparr/water-ownership/pull/14
